name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install ubuntu Deps
        run: sudo apt-get install -y pandoc graphviz
      - name: Install python Deps
        run: |
          python -m pip install -r requirements.txt
      - name: Build Docs
        run: sphinx-build -b html -j auto ./docs/ ./docs/_build/html
      - name: Compress Artifacts
        run: |
          mkdir artifacts
          tar -zcvf html_docs.tar.gz docs/_build/html
          mv html_docs.tar.gz artifacts/.
      - uses: actions/upload-artifact@v2
        with:
          name: html_docs
          path: artifacts
